# Generated by Django 2.1.5 on 2019-01-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(),
        ),
    ]
