# Generated by Django 2.1.5 on 2019-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0004_remove_employee_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_Requests', models.IntegerField()),
                ('number_of_get', models.IntegerField()),
                ('number_of_post', models.IntegerField()),
                ('number_of_put', models.IntegerField()),
                ('number_of_delete', models.IntegerField()),
                ('number_of_connect', models.IntegerField()),
                ('number_of_options', models.IntegerField()),
                ('number_of_trace', models.IntegerField()),
                ('number_of_head', models.IntegerField()),
            ],
        ),
    ]
