# Generated by Django 2.1.5 on 2019-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0005_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentRequst', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD'), ('PUT', 'PUT'), ('HEAD', 'HEAD'), ('DELETE1', 'DELETE1'), ('TRACE', 'TRACE')], max_length=10)),
                ('timeToProcess', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
