# Generated by Django 2.1.5 on 2019-03-12 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0007_auto_20190312_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_connect',
            new_name='numberOFGET',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_delete',
            new_name='numberOfConnect',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_get',
            new_name='numberOfDelete',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_head',
            new_name='numberOfHead',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_options',
            new_name='numberOfOptions',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_post',
            new_name='numberOfPost',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_put',
            new_name='numberOfPut',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='number_of_trace',
            new_name='numberOfTrace',
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimeConnect',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimeDelete',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimeGet',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimeHead',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimeOptions',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimePost',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimePut',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='avgResponseTimeTrace',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
