# Generated by Django 2.1.5 on 2019-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0008_auto_20190312_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='numberOFGET',
            new_name='numberOFGet',
        ),
        migrations.AlterField(
            model_name='request',
            name='currentRequest',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD'), ('PUT', 'PUT'), ('CONNECT', 'CONNECT'), ('DELETE1', 'DELETE1'), ('TRACE', 'TRACE')], max_length=10),
        ),
    ]
