# Generated by Django 2.1.5 on 2019-03-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0009_auto_20190312_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='numberOFGet',
            new_name='numberOfGet',
        ),
    ]
