# Generated by Django 2.1.5 on 2019-03-12 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0010_auto_20190312_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='avgResponseTimeConnect',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='avgResponseTimeHead',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='avgResponseTimeTrace',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='numberOfConnect',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='numberOfHead',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='numberOfTrace',
        ),
        migrations.AddField(
            model_name='request',
            name='creationTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='deleteNumberInPastHour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='deleteNumberInPastMin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='getNumberInPastHour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='getNumberInPastMin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='optionsNumberInPastHour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='optionsNumberInPastMin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='postNumberInPastHour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='postNumberInPastMin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='putNumberInPastHour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='putNumberInPastMin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='currentRequest',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('OPTIONS', 'OPTIONS'), ('PUT', 'PUT'), ('DELETE1', 'DELETE1')], max_length=10),
        ),
    ]
