# Generated by Django 2.1.5 on 2019-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0011_auto_20190312_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_Requests', models.IntegerField()),
            ],
        ),
    ]
